### ISSUE TITLE
Vein Mining in the Nether Deletes Tool & Gives Buttons

### ISSUE THREAD

**Issue by spunkyjethro** [Elemend/Vein-Miner-Unified#13]
Using vein miner in the nether replaces your tool with the block you are breaking and gives you stone buttons for the other blocks that break.

This is happening with all tool types and all material types as well. I've also tested with each setting on and off, the results are the same
![Capture](https://user-images.githubusercontent.com/2007473/85816445-f2eaaa80-b730-11ea-9ffd-cf35d1e39c10.PNG)
.

**Comment by Elemend** [comment]
seems to me like the data pack doesn't have access to the loaded chunk. This makes the most sense to me because not only does the tool get destroyed, but also the blocks don't drop the correct items. I tested it in a fresh 1.16.1 world and mining in the nether worked there. I don't know if there's something interfering here?

**Comment by spunkyjethro** [comment]
I've done some more testing. The world it's happening in has been upgraded from 1.15-1.16, this is the first time I've had any issues. I just created a new world in 1.15.2 with vein miner for that version, upgraded and tried the new vein miner with no issue. So it seems like it's exclusive to my 1 world for whatever reason.

Is there something that needs to be done to give access to chunks? I've never heard of that before.

**Comment by spunkyjethro** [comment]
Looks like I've resolved the issue. I uninstalled using the command and reinstalled the newest version once again. Seems to be working correctly.
