### ISSUE TITLE
1.14pre2 - block regognition issues

### ISSUE THREAD

**Issue by digital-r** [Elemend/Vein-Miner-Unified#2]
Find some bugs in current version of this branch under 1.14pre2.
- nether quartz ore give no drops when mined using diamond vein-miner pickaxe;
- ores mined with vein-miner pickaxe from bottom side not toggle vein-mining.
- Vein-mining ores from top side frequently triggers digging-up whole 9x9x9 area. All mined blocks drops as ore (up to 700+ ore blocks). Also, this leave zero dyrability on tool, even if tool previously have full durability.
Unfortunately, there is no errors in logs.

**Comment by Elemend** [comment]
Ok, the first Issue was a typo. The second is propably caused by some hitbox changes in the latest snapshots, should be easy enough too adjust. The third one though... that might be a systematic error. Not sure what I can do about that just yet.

**Comment by digital-r** [comment]
Some updates:
- From-below-block-mining works. But not always. So, its really looks like a hitbox issues.
- 9x9x9 spontaneous digging are really strange. I have this issue only with non-metall ores.
- Woodcutting with vein-miner axe have non-critical issues with ground level logs and dark oak trees (may be due to different blockstates?).

**Comment by Elemend** [comment]
- I think I have some clues on why that problem with the 9x9x9 mined areas happens. I have a hard time to replicate this though. Maybe you happen to know if that problem also occurs in the 1.13.2-Version?
- The dark oak trees had a problem where I was missing a word in the filepath. I think that was the Issue here.

**Comment by Elemend** [comment]
Alright, I uploaded an updated version. I hope I managed to fix the spontaneus 9x9x9 diggings and Issues with dark oak. Let me know if they persist or if any other Issues occur.

**Comment by TheSofas** [comment]
Still having issues with the 9x9x9 digging from above. I have the latest version. It seems to change all "stone" to the "non-ore" you mined, and avoids all other blocks and ores. Here's a screenshot.
https://imgur.com/a/EKsDE8u

**Comment by TheSofas** [comment]
An update:

I tried the 1.13.2 version as well (in 1.14), and it has the same issues. For me, it only seems to happen about 30% of the time, and has only happened with coal, and iron.

**Comment by Elemend** [comment]
I can recreate the Issue now. This doesn't mean that I would know how to fix this though. I have no Idea.

...It's a sytematic Issue too. Has nothing to do what Blocks you mine. It's just that it's most noticeable with ores and stone, since that is what you'd encounter mostly, but it might as well happen with red and black wool. I'm completely baffled that I have made this and now I don't understand it anymore, it's ridiculous. I'm open to all input to narrow this down.

...Some time later. I think this is a directional Issue. As far as I can tell it only happens when you veinmine while looking in the negative x direction and negative z direction. In the positive directions i can't recreate this Issue.

**Comment by Elemend** [comment]
Well, that took some digging into the commands. I got it fixed. I'd appreciate it to if you could confirm that as well.

**Comment by TheSofas** [comment]
Seems to be fixed, I can't recreate the issue in any direction, on any type of ore, or block. I've tried both versions. Glad to see it got fixed! Seems ready for a new Reddit post for the new 1.14 players, eh?
