### ISSUE TITLE
Request: tree "mining" should remove leaves

### ISSUE THREAD

**Issue by pbhj** [Elemend/Vein-Miner-Unified#25]
I'd love it if the tree "mining" using vein-miner would remove the leaves too. Is there a reason not to do that, ideally if you have a pair of shears it would prune the leaves when you chop down the lowest block, that way you wouldn't lose drops of saplings/apples/whatever; but that's perhaps being too fussy.

I see there are files like  Vein-Miner-Unified/vein_miner_unified/data/vm/functions/blocks/logs/oak_wood.mcfunction , but also "stripped" versions for each of the tree types. Perhaps the regular position oak_wood (and similar woods) should also break the blocks if they're the relevant leaf type too? That seems naively like it would work.

**Comment by Elemend** [comment]
I mean... the only reason is this being a vein miner data pack, not a timber data pack. I get what you're saying, but that's the one core mechanic this pack follows: mine the same type of blocks.
Another thing why I'd rather not add this is because the distance to mine the blocks in is 5 Blocks outwards, so if there is a log remaining should the leaves stay? If no I have no way to know this. The way the mining works doesn't allow for this. It would require a significant rewrite...

**Comment by Elemend** [comment]
yeah, no. I'm definetly not going to do this. It's outside of the scope of what I intended doing with this data pack.
